version: '3.8'

services:
  # 1. SQL Server Container
  carrental-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carrental-sql-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=CarRentalP@ssword2026!
    ports:
    - "1433:1433"

    networks:
    - carrental-network

  # 2. CarRental API Container
  carrental-api:
    image: carrental-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carrental-api-app
    ports:  
    - "8080:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=carrental-db;Database=CarRentalDB;User Id=sa;Password=CarRentalP@ssword2026!;TrustServerCertificate=True;
    depends_on:
      - carrental-db
    networks:
      - carrental-network

networks:
  carrental-network:
    driver: bridge